package co.swisapp.swis.utility;

import android.content.Context;
import android.os.Environment;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public abstract class FileHelper {

    public static int TYPE_INTERNAL = 0x03;
    public static int TYPE_EXTERNAL = 0x07;


    /**
     * Generates the video file using the current timeStamp.
     * @return Filename based on time
     */
    public static String generateVideoFileName(){
        String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss",
                Locale.getDefault()).format(new Date());
        return "VID_" + timeStamp + ".mp4";
    }

    /**
     * This method creates a new directory if it doesn't exist and returns the new file
     * made to the recording method to assign file name to the videos.
     * @param context Taking in the context as param
     * @param filename Name of the file as generated by {@link #generateVideoFileName()}
     * @param fileType filetype can be {@link #TYPE_INTERNAL} or {@link #TYPE_EXTERNAL}
     * @return new File with attribute filename
     */
    public static File createVideoFile(Context context, String filename, int fileType){
        if(fileType == 0x03){
            File folder = context.getDir("Videos", Context.MODE_PRIVATE) ;
            return new File(folder.getPath() + File.separator + filename) ;
        }
        else if(fileType == 0x07){
            File folder = new File(Environment.getExternalStorageDirectory() +  "/swisapp") ;
            if(!folder.exists()){
                folder.mkdirs() ;
            }
            return new File(folder.getPath() + File.separator + filename) ;
        }
        return new File("void") ;
    }
}
